### ISSUE TITLE
A little more complexity

### ISSUE THREAD

**Issue by jeffsegal** [bohnman/squiggly-filter-jackson#1]
Using your example JSON, let's say that I wanted to return all attributes but only the `firstName` of `assignee`'s. Should I be able to specify that as `**,assignee{firstName}`? Or some other way? Or perhaps this isn't supported (yet)?

For what it's worth, when I use the above syntax, I end up with everything, so it seems like the `**` overrode the subsequent attribute filters.

BTW great job with the library; it's a very useful capability and pretty easy to integrate (using a fairly standard Spring web app in my case).

**Comment by bohnman** [comment]
@jeffsegal This is a great suggestion and shouldn't be too hard to implement.  I'll try to get to this soon.

**Comment by bohnman** [comment]
@jeffsegal I have added the capability you requested.

To clarify, the filter logic now chooses the **most specific**  filter that matches the property.  Specificity is determined using the following logic:

- an exact name is the most specific
- a ** is the least specific
- a * is the second to least specific
- otherwise, the number of non-wildcard characters is counted, the higher the number, the more specific
- if two filters have the same specificity, the latter one is chosen

I also implemented a new feature that allows you to exclude fields by prefix the field name with a minus sign.  For example, a filter of `**,-assignee` would include all fields except the assignee field.

Please let me know if this works for you so the issue can be closed.

**Comment by jeffsegal** [comment]
Very cool. Just to make sure I'm following correctly, when iterating through properties, the logic will look at the provided filter String for the most specific filter to that property and choose it, correct? E.g., when processing the `assignee` property, if the filter string is `**,foo`, it'll include the entire `assignee` object because `**` is the most specific match, but if it's `**,assignee{firstName}`, it'll only include the `firstName` of the `assignee`?

**Comment by bohnman** [comment]
You got it.

**Comment by jeffsegal** [comment]
Excellent. This should definitely work for us and thanks again.

**Comment by bohnman** [comment]
No problem.  Closing issue.
