### ISSUE TITLE
Both Squiggly filter and Jackson serializer

### ISSUE THREAD

**Issue by GiulianoFranchetto** [bohnman/squiggly-filter-jackson#14]
Hi,

I'm trying to integrate Squiggly in our spring boot application, where we use a bunch of custom serializers.

Apparently, we can't make both the filter and our serializers live together, as only one is called. For example, when I enable a `JsonSerializer<User>`, adding `?fields=... ` in the URL does nothing.

If I disable my serializer, Squiggly does its job.

Is it possible to make both work? Like first calling the serializer and then the filter to remove unwanted fields?

Best regards

**Comment by bohnman** [comment]
@GiulianoFranchetto I would be happy to look into this.  Would you provide me with a standalone example exhibiting this behavior?  It would be a great help.

Thanks!

~Ryan

**Comment by GiulianoFranchetto** [comment]
@bohnman Hi!

I created a small project to show the behaviour: see [here](https://github.com/GiulianoFranchetto/squiggly-jackson)

By default, spring adds the `TestSerializer`. If you request localhost:8090, you should see `{"a":"a","c":"c"}`

If you request   localhost:8090?fields=a, the response remains the same.

If you comment the line `@JsonComponent` of `TestSerializer` and rerun the server, localhost:8090?fields=a return only field a, but localhost:8090 returns `{"a":"a","b":"b","c":"c"}`, as the serializer is disabled.

Thanks for your help !

**Comment by bohnman** [comment]
@GiulianoFranchetto Squiggly is implemented as a PropertyFilter.  The problem is that when you use JsonGenerator jgen directly in your serializer, you are bypassing the filter.

Unfortunately, there is no good answer without rewriting your serializer or somehow using a custom JsonGenerator (which seems like it would be very error prone).  

If you were willing to rewrite your serializer, you could do something like the following:

```java
@JsonComponent
public class TestSerializer extends JsonSerializer<TestObject> {

	@Override
	public void serialize(TestObject value, JsonGenerator jgen, SerializerProvider provider) throws IOException {
		Map<String, Object> map = new HashMap<>();
		map.put("a", value.getA());
		map.put("c", value.getC());

		provider.defaultSerializeValue(map, jgen);
	}
}
```

Depending on your use case, you could also look into just using jackson annotations to customize the serialization.

Sorry!  I wish I had a better response!

~Ryan

**Comment by GiulianoFranchetto** [comment]
@bohnman I just rewritted my serializers, and everything is working fine now.

Maybe we could add a section in the ReadMe or wiki, as adding Squiggly may not work on already existing projects using serializers?

Thank you for your help !

**Comment by bohnman** [comment]
@GiulianoFranchetto I've added a Limitations section to the README that describes this particular scenario.
